# TO SEE FULL CONFIG: helm show values redis --repo https://charts.bitnami.com/bitnami --version 20.3.0

## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
##
architecture: standalone
## Redis&reg; Authentication parameters
auth:
  ## @param auth.enabled Enable password authentication
  enabled: false

master:
  ## @param master.count Number of Redis&reg; master instances to deploy (experimental, requires additional configuration)
  count: 1
  ## @param master.kind Use either Deployment, StatefulSet (default) or DaemonSet
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
  kind: Deployment
  ## Persistence parameters
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  persistence:
    ## @param master.persistence.enabled Enable persistence on Redis&reg; master nodes using Persistent Volume Claims
    enabled: false
    ## @param master.persistence.medium Provide a medium for `emptyDir` volumes.

tls:
  ## @param tls.enabled Enable TLS traffic
  enabled: false
